import { weaponLabel } from '../../utils/labels';
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { DamageRules, Weapon } from '../../domain/weapon/schema';
import type { DamageSettings } from '../../domain/damage/calculateDamage';
import { calculateDamage } from '../../domain/damage/calculateDamage';
export default function DamageChart({ weapon, state, rules }: { weapon: Weapon; state: DamageSettings; rules: DamageRules }) {
  const points = weapon.falloff.map(point => ({ distance: point.distance, base: point.damage, chest: calculateDamage(weapon, 'chest', { ...state, distance: point.distance, pellets: 1 }, rules).damage, head: calculateDamage(weapon, 'head', { ...state, distance: point.distance, pellets: 1 }, rules).damage }));
  return <div className="chart" role="img" aria-label={`${weaponLabel(weapon)} 거리별 피해 그래프. 동일한 수치는 바로 아래 거리 표에서 확인할 수 있습니다.`}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{ top: 12, right: 18, left: -15, bottom: 5 }} accessibilityLayer><CartesianGrid stroke="#2b352e" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="distance" type="number" domain={[weapon.measuredRange.min, weapon.measuredRange.max]} tick={{ fill: '#97a39b', fontSize: 12 }} tickLine={false} axisLine={false} unit="m"/><YAxis tick={{ fill: '#97a39b', fontSize: 12 }} tickLine={false} axisLine={false}/><Tooltip contentStyle={{ background: '#1b231e', border: '1px solid #415040', borderRadius: 8 }} labelFormatter={label => `${label}m`} formatter={value => typeof value === 'number' ? value.toFixed(3) : String(value ?? '—')}/><Legend wrapperStyle={{ fontSize: 13 }}/><Line type="linear" dataKey="base" name="기본 데미지" stroke="#a2aaa5" strokeWidth={2} dot={false} isAnimationActive={false}/><Line type="linear" dataKey="chest" name="가슴" stroke="#c9ed85" strokeWidth={2} dot={false} isAnimationActive={false}/><Line type="linear" dataKey="head" name="머리" stroke="#82b6e0" strokeWidth={2} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>;
}
