import { ammoLabel, bodyLabels, categoryLabels, firingLabels, patchDateLabel, weaponLabel } from '../../utils/labels';
import { lazy, Suspense } from 'react';
import { ArrowLeft, ArrowUpRight, History, Package, Activity } from 'lucide-react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import type { Dataset } from '../../hooks/useDataset';
import { parseUrlState, updateUrlState } from '../../utils/urlState';
import type { ExplorerState } from '../../utils/urlState';
import { Controls } from '../../components/common/Controls';
import { BodyPanel } from '../../components/common/BodyPanel';
import { calculateDamage } from '../../domain/damage/calculateDamage';
import { metric, number } from '../../utils/format';
const DamageChart = lazy(() => import('./DamageChart'));
const changeLabels: Record<string, string> = { damage: '데미지', recoil: '반동', 'fire rate': '연사 속도', attachments: '부착물', handling: '조작성', 'spawn rate': '스폰', added: '무기 추가', removed: '무기 삭제', other: '기타 변경' };
export function Detail({ data }: { data: Dataset }) {
  const { slug } = useParams();
  const [params, setParams] = useSearchParams();
  const weapon = data.weapons.find(w => w.slug === slug);
  const state = parseUrlState(params, Math.max(...data.weapons.map(w => w.measuredRange.max)));
  const update = (patch: Partial<ExplorerState>) => setParams(updateUrlState(new URLSearchParams(window.location.search), patch), { replace: true });
  if (!weapon) return <div className="empty"><h1>무기를 찾을 수 없습니다</h1><Link to="/weapons">무기 목록으로 돌아가기</Link></div>;
  const patches = data.patches.filter(p => p.weaponId === weapon.id);
  const representative = calculateDamage(weapon, state.body, state, data.rules);
  const explorerParams = updateUrlState(params, { weapon: weapon.id });
  return <><Link className="back-link" to={`/weapons?${explorerParams}`}><ArrowLeft size={15}/> 무기 목록</Link><div className="page-heading detail-heading"><div><div className="eyebrow">무기 상세 / {categoryLabels[weapon.category]}</div><h1>{weaponLabel(weapon)}<span className="heading-dot">.</span></h1><p>{ammoLabel(weapon.ammoType)} <span className="divider">/</span> {firingLabels[weapon.firing.kind]} {weapon.carePackage && <span className="care-label"><Package size={14}/> 보급 전용</span>} {weapon.status === 'archived' && <span className="archive-badge">삭제된 무기 · 보관 데이터</span>}</p></div><a className="source-link" href={weapon.source.sourceUrl} target="_blank" rel="noreferrer">데이터 출처 <ArrowUpRight size={15}/></a></div><div className="detail-summary panel"><div><span>기본 데미지</span><strong>{number(weapon.baseDamage)}</strong><small>{weapon.baseDamage === null ? '총구 수치 미확인' : weapon.projectile.kind === 'pellets' ? '1펠릿 기준' : '총구 기준'}</small></div><div><span>분당 발사속도</span><strong>{weapon.firing.rpm ?? '—'}<em>RPM</em></strong><small>공개 표시값 · 기본 모드</small></div><div><span>측정 거리</span><strong>{weapon.measuredRange.min}–{weapon.measuredRange.max}<em>m</em></strong><small>구간 밖 피해 미확인</small></div><div><span>총구 속도</span><strong>{weapon.muzzleVelocity ?? '—'}<em>m/s</em></strong><small>{weapon.muzzleVelocity === null ? '확인된 자료 없음' : '공개 패치 기록'}</small></div></div>
    <div className="workspace detail-workspace"><Controls state={state} update={update} maxDistance={Math.max(...data.weapons.map(w => w.measuredRange.max))} rules={data.rules}/><div className="detail-content"><section className="panel detail-section"><div className="section-heading"><span><Activity size={17}/> 거리별 데미지 감소</span><span className="micro">선형 보간</span></div><p className="hint">현재 방어구 기준 · 1발{weapon.projectile.kind === 'pellets' ? '의 1펠릿' : ''} 피해. 공개 표본 사이를 선형으로 연결합니다.</p><Suspense fallback={<div className="chart empty">그래프를 불러오는 중…</div>}><DamageChart weapon={weapon} state={state} rules={data.rules}/></Suspense><details><summary>거리별 수치 표 ({weapon.falloff.length}개 표본)</summary><div className="table-scroll"><table><thead><tr><th>거리</th><th>기본</th><th>가슴</th><th>머리</th></tr></thead><tbody>{weapon.falloff.map(point => <tr key={point.distance}><th>{point.distance}m</th><td>{number(point.damage)}</td><td>{number(calculateDamage(weapon, 'chest', { ...state, distance: point.distance, pellets: 1 }, data.rules).damage)}</td><td>{number(calculateDamage(weapon, 'head', { ...state, distance: point.distance, pellets: 1 }, data.rules).damage)}</td></tr>)}</tbody></table></div></details></section>
    <section className="panel detail-section"><div className="section-heading"><span>배율과 부위별 결과</span><span className="micro">{state.distance} m</span></div><p className="hint">{weapon.projectile.kind === 'pellets' ? `${state.pellets === 'all' ? weapon.projectile.pelletCount : state.pellets}펠릿이 같은 부위에 명중한 1발의 피해 · HTK는 발사 횟수` : '같은 부위 연속 명중 기준'}</p>{representative.reason === 'range' && <p className="warning">선택한 거리는 이 무기의 측정 범위 밖입니다.</p>}<div className="table-scroll"><table><thead><tr><th>부위</th><th>부위 배율</th><th>무기 배율</th><th>방어구 배율</th><th>데미지</th><th>필요 탄수 (HTK)</th><th>처치 시간 (TTK)</th></tr></thead><tbody>{data.rules.bodyParts.map(part => { const r = calculateDamage(weapon, part.id, state, data.rules); return <tr key={part.id} className={state.body === part.id ? 'highlight-row' : ''}><th>{bodyLabels[part.id]}</th><td>{number(r.hitMultiplier, 2)}</td><td>{number(r.classMultiplier, 2)}</td><td>{part.armor === 'none' ? '—' : number(r.armorMultiplier, 2)}</td><td className="accent">{number(r.damage)}</td><td>{r.htk ?? '—'}</td><td>{metric(r.ttk, 'ttk')}</td></tr>; })}</tbody></table></div></section>
    <section className="panel detail-section"><div className="section-heading"><span>계산 메모</span></div><ul className="notes-list"><li>공개 데미지는 소수점 한 자리 표본입니다. 계산 중 반올림하지 않지만 실제 게임과 경계 HTK가 다를 수 있습니다.</li><li>TTK: {state.timing === 'perfect' ? '공개 RPM 기반 최소 간격 모델' : state.timing === 'normal' ? '화면에서 관찰한 TTK 기반 근사 간격' : `클릭 간격 ${state.clickIntervalMs}ms 기반 시뮬레이션`}. 볼트액션은 별도 조준경 간격을 사용합니다.</li>{weapon.firing.kind === 'burst' && <li>{weapon.firing.burstSize}점사 · 내부 간격 {number(weapon.firing.intraBurstInterval, 4)}초. 점사 경계 지연을 별도로 계산합니다.</li>}{weapon.firing.cycleLimit !== null && <li>{weapon.firing.cycleLimit}발을 초과하면 재장전/추가 작동 시간이 미확인이므로 TTK는 —입니다.</li>}{weapon.projectile.kind === 'pellets' && <li>최대 {weapon.projectile.pelletCount}펠릿. 현재 부위 1펠릿 {number(representative.perPellet)} 데미지. 분산·서로 다른 부위 명중은 시뮬레이션하지 않습니다.</li>}{weapon.projectile.kind === 'slug' && <li>O12는 단일 슬러그입니다. 펠릿 설정을 곱하지 않습니다.</li>}{weapon.id === 'dragunov' && <li>머리·목 무기 배율 2.80의 개별 예외를 적용합니다.</li>}{weapon.id === 'win94' && <li>고정 조준경: 모든 조준 선택은 동일한 관찰 간격을 사용합니다.</li>}</ul></section>
    <section className="panel detail-section"><div className="section-heading"><span><History size={17}/> 패치 기록</span><span className="micro">{patches.length}건</span></div><p className="hint">확인된 변경 종류와 수치 요약입니다. 상세 맥락은 각 공식 패치에서 확인하세요.</p><ol className="patch-list">{patches.map(patch => <li key={`${patch.patch}-${patch.weaponId}`}><div><strong>{patch.patch}</strong><small>{patchDateLabel(patch.date)}</small><a href={patch.sourceUrl} target="_blank" rel="noreferrer">공식 패치 <ArrowUpRight size={13}/></a></div><ul>{patch.changes.map((change, i) => <li key={i}><span className={`change-tag ${change.direction}`}>{change.direction === 'buff' ? '상향' : change.direction === 'nerf' ? '하향' : '변경'}</span>{changeLabels[change.type] ?? change.type}{change.figures.length > 0 && <span className="muted"> · 기록 수치: {change.figures.join(' / ')}</span>}</li>)}</ul></li>)}</ol>{patches.length === 0 && <p className="hint">확인된 변경 이력이 없습니다.</p>}</section></div><BodyPanel weapon={weapon} state={state} rules={data.rules} update={update}/></div></>;
}
