import { bodyLabels } from '../../utils/labels';
import { Crosshair, RotateCcw, Settings2, Shield, SlidersHorizontal } from 'lucide-react';
import type { DamageRules } from '../../domain/weapon/schema';
import { scopes } from '../../domain/weapon/schema';
import type { ExplorerState } from '../../utils/urlState';
interface Props { state: ExplorerState; update: (patch: Partial<ExplorerState>) => void; maxDistance: number; rules: DamageRules }
export function Controls({ state, update, maxDistance, rules }: Props) {
  return <aside className="controls panel" aria-label="계산 조건">
    <div className="section-heading"><span><SlidersHorizontal size={16}/> 계산 조건</span><button className="icon-button" title="계산 조건 초기화" aria-label="계산 조건 초기화" onClick={() => update({ distance: 0, helmet: 2, vest: 2, timing: 'perfect', clickIntervalMs: 200, scope: '4x', pellets: 'all', body: 'chest', rpmMode: 'default' })}><RotateCcw size={15}/></button></div>
    <div className="control-block"><label className="label" htmlFor="distance">교전 거리 <Crosshair size={15}/></label><div className="distance-value"><input id="distance" type="number" min={0} max={maxDistance} value={state.distance} onChange={e => update({ distance: Math.min(maxDistance, Math.max(0, Number(e.target.value) || 0)) })}/><span>미터</span></div><input className="range" aria-label="교전 거리 슬라이더" type="range" min={0} max={maxDistance} step={1} value={state.distance} onChange={e => update({ distance: Number(e.target.value) })}/><div className="range-labels"><span>0 m</span><span>{maxDistance} m</span></div></div>
    {(['helmet', 'vest'] as const).map(armor => <fieldset className="control-block" key={armor}><legend><Shield size={15}/> {armor === 'helmet' ? '헬멧' : '방탄조끼'}</legend><div className="segmented">{([0, 1, 2, 3] as const).map(level => <button key={level} aria-pressed={state[armor] === level} onClick={() => update({ [armor]: level })}>{level === 0 ? '없음' : `${level}레벨`}</button>)}</div><p className="hint">피해 감소 {Math.round((1 - rules.armor[state[armor]]) * 100)}%</p></fieldset>)}
    <div className="control-block"><label className="label" htmlFor="body-part">기준 부위</label><select id="body-part" value={state.body} onChange={e => { const body = rules.bodyParts.find(p => p.id === e.target.value); if (body) update({ body: body.id }); }}>{rules.bodyParts.map(part => <option key={part.id} value={part.id}>{bodyLabels[part.id]}</option>)}</select><p className="hint">카드와 정렬에 동일하게 적용됩니다.</p></div>
    <div className="control-block"><label className="label" htmlFor="pellets">산탄 명중 수</label><select id="pellets" value={state.pellets} onChange={e => update({ pellets: e.target.value === 'all' ? 'all' : Number(e.target.value) })}><option value="all">전체 펠릿 명중</option>{Array.from({ length: 9 }, (_, i) => <option key={i} value={i + 1}>{i + 1} 펠릿</option>)}</select><p className="hint">같은 부위 명중 기준 · 탄종별 최대 수 적용</p></div>
    <details className="advanced" open={state.timing !== 'perfect' || state.scope !== '4x'}><summary><Settings2 size={15}/> 발사 타이밍</summary><div className="advanced-inner"><label className="label" htmlFor="timing">단발 / 점사</label><select id="timing" value={state.timing} onChange={e => { if (e.target.value === 'normal' || e.target.value === 'perfect' || e.target.value === 'custom') update({ timing: e.target.value }); }}><option value="perfect">최적 간격 · 이론값</option><option value="normal">일반 사격 · 관찰값</option><option value="custom">직접 설정</option></select>{state.timing === 'custom' && <label className="field">클릭 간격 (ms)<input type="number" min={1} max={5000} value={state.clickIntervalMs} onChange={e => update({ clickIntervalMs: Math.min(5000, Math.max(1, Number(e.target.value) || 1)) })}/></label>}<label className="field">볼트액션 조준경<select value={state.scope} onChange={e => { const scope = scopes.find(s => s === e.target.value); if (scope) update({ scope }); }}>{scopes.map(scope => <option key={scope} value={scope}>{scope === 'none' ? '비조준' : scope}</option>)}</select></label><label className="field">선택식 연사 모드<select value={state.rpmMode} onChange={e => update({ rpmMode: e.target.value === 'slow' ? 'slow' : 'default' })}><option value="default">기본 · MG3 990 RPM</option><option value="slow">저속 · MG3 660 RPM</option></select></label><p className="hint">클릭 간격은 점사 시작 사이의 시간입니다. 볼트 타이밍은 조준경별 관찰값을 사용합니다.</p></div></details>
    <div className="conditions-foot"><span className="status-dot"/> {rules.health} HP · 첫 발 0초<br/><span>전탄 명중 · 비행시간 제외</span></div>
  </aside>;
}
