import { ammoLabel, bodyLabels, timingLabels, weaponLabel } from '../../utils/labels';
import { ArrowLeftRight, X } from 'lucide-react';
import type { DamageRules, Weapon } from '../../domain/weapon/schema';
import { calculateDamage } from '../../domain/damage/calculateDamage';
import type { ExplorerState } from '../../utils/urlState';
import { metric, number } from '../../utils/format';
export function Comparison({ first, second, state, rules, update }: { first: Weapon; second: Weapon; state: ExplorerState; rules: DamageRules; update: (patch: Partial<ExplorerState>) => void }) {
  const a = calculateDamage(first, state.body, state, rules);
  const b = calculateDamage(second, state.body, state, rules);
  return <section className="comparison panel" aria-labelledby="compare-heading"><div className="section-heading"><span><ArrowLeftRight size={17}/> 동일 조건 비교</span><button className="icon-button" aria-label="비교 닫기" onClick={() => update({ compare: '' })}><X size={17}/></button></div><div className="comparison-title"><h2 id="compare-heading">{weaponLabel(first)} <span>대</span> {weaponLabel(second)}</h2><button className="text-button" onClick={() => update({ weapon: second.id, compare: first.id })}>순서 바꾸기 <ArrowLeftRight size={14}/></button></div><p className="hint">{state.distance}m · 헬멧 {state.helmet}레벨 · 조끼 {state.vest}레벨 · {bodyLabels[state.body]} · {timingLabels[state.timing]}</p><div className="table-scroll"><table><caption className="sr-only">대표 지표 비교</caption><thead><tr><th>대표 지표</th><th>{weaponLabel(first)}</th><th>{weaponLabel(second)}</th></tr></thead><tbody>{(['damage', 'htk', 'ttk'] as const).map(type => <tr key={type}><th>{type === 'damage' ? '데미지' : type === 'htk' ? '처치 필요 탄수 (HTK)' : '처치 시간 (TTK)'}</th><td className="accent">{metric(a[type], type)}</td><td className="blue">{metric(b[type], type)}</td></tr>)}<tr><th>분당 발사속도 (RPM)</th><td>{number(a.rpm, 0)}</td><td>{number(b.rpm, 0)}</td></tr><tr><th>탄약</th><td>{ammoLabel(first.ammoType)}</td><td>{ammoLabel(second.ammoType)}</td></tr></tbody></table></div><details open><summary>13개 부위 비교 · 데미지 / 필요 탄수 / 처치 시간</summary><div className="table-scroll"><table><thead><tr><th>부위</th><th>{weaponLabel(first)}</th><th>{weaponLabel(second)}</th></tr></thead><tbody>{rules.bodyParts.map(part => { const left = calculateDamage(first, part.id, state, rules); const right = calculateDamage(second, part.id, state, rules); return <tr key={part.id}><th>{bodyLabels[part.id]}</th>{[left, right].map((result, i) => <td key={i}><span className={i === 0 ? 'accent' : 'blue'}>{number(result.damage)}</span><span className="cell-secondary">{result.htk ?? '—'}발 / {metric(result.ttk, 'ttk')}</span></td>)}</tr>; })}</tbody></table></div></details></section>;
}
